FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# TODO: cuando exista el build de Angular (dist/), copiarlo aquí:
# COPY --from=frontend-build /app/dist/frontend/browser /usr/share/nginx/html
